// Code generated by "stringer -type=OpType"; DO NOT EDIT.

package code

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpADC-0]
	_ = x[OpADD-1]
	_ = x[OpAND-2]
	_ = x[OpBIT-3]
	_ = x[OpCALL-4]
	_ = x[OpCCF-5]
	_ = x[OpCP-6]
	_ = x[OpCPL-7]
	_ = x[OpDAA-8]
	_ = x[OpDEC-9]
	_ = x[OpDI-10]
	_ = x[OpEI-11]
	_ = x[OpHALT-12]
	_ = x[OpINC-13]
	_ = x[OpJP-14]
	_ = x[OpJR-15]
	_ = x[OpLD-16]
	_ = x[OpLDH-17]
	_ = x[OpNOP-18]
	_ = x[OpOR-19]
	_ = x[OpPOP-20]
	_ = x[OpPREFIX-21]
	_ = x[OpPUSH-22]
	_ = x[OpPrefix-23]
	_ = x[OpRES-24]
	_ = x[OpRET-25]
	_ = x[OpRETI-26]
	_ = x[OpRL-27]
	_ = x[OpRLA-28]
	_ = x[OpRLC-29]
	_ = x[OpRLCA-30]
	_ = x[OpRR-31]
	_ = x[OpRRA-32]
	_ = x[OpRRC-33]
	_ = x[OpRRCA-34]
	_ = x[OpRST-35]
	_ = x[OpSBC-36]
	_ = x[OpSCF-37]
	_ = x[OpSET-38]
	_ = x[OpSLA-39]
	_ = x[OpSRA-40]
	_ = x[OpSRL-41]
	_ = x[OpSTOP-42]
	_ = x[OpSUB-43]
	_ = x[OpSWAP-44]
	_ = x[OpXOR-45]
}

const _OpType_name = "OpADCOpADDOpANDOpBITOpCALLOpCCFOpCPOpCPLOpDAAOpDECOpDIOpEIOpHALTOpINCOpJPOpJROpLDOpLDHOpNOPOpOROpPOPOpPREFIXOpPUSHOpPrefixOpRESOpRETOpRETIOpRLOpRLAOpRLCOpRLCAOpRROpRRAOpRRCOpRRCAOpRSTOpSBCOpSCFOpSETOpSLAOpSRAOpSRLOpSTOPOpSUBOpSWAPOpXOR"

var _OpType_index = [...]uint8{0, 5, 10, 15, 20, 26, 31, 35, 40, 45, 50, 54, 58, 64, 69, 73, 77, 81, 86, 91, 95, 100, 108, 114, 122, 127, 132, 138, 142, 147, 152, 158, 162, 167, 172, 178, 183, 188, 193, 198, 203, 208, 213, 219, 224, 230, 235}

func (i OpType) String() string {
	if i >= OpType(len(_OpType_index)-1) {
		return "OpType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _OpType_name[_OpType_index[i]:_OpType_index[i+1]]
}
