// Code generated by "stringer -type ValueLocation"; DO NOT EDIT.

package code

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ValA-0]
	_ = x[ValB-1]
	_ = x[ValC-2]
	_ = x[ValD-3]
	_ = x[ValE-4]
	_ = x[ValF-5]
	_ = x[ValAF-6]
	_ = x[ValBC-7]
	_ = x[ValDE-8]
	_ = x[ValHL-9]
	_ = x[ValSP-10]
	_ = x[ValPC-11]
	_ = x[Val8-12]
	_ = x[Val16-13]
	_ = x[ValAddress-14]
	_ = x[ValRegister-15]
}

const _ValueLocation_name = "ValAValBValCValDValEValFValAFValBCValDEValHLValSPValPCVal8Val16ValAddressValRegister"

var _ValueLocation_index = [...]uint8{0, 4, 8, 12, 16, 20, 24, 29, 34, 39, 44, 49, 54, 58, 63, 73, 84}

func (i ValueLocation) String() string {
	if i < 0 || i >= ValueLocation(len(_ValueLocation_index)-1) {
		return "ValueLocation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ValueLocation_name[_ValueLocation_index[i]:_ValueLocation_index[i+1]]
}
