// Code generated by "stringer -type=MultiRegister -linecomment"; DO NOT EDIT.

package engine

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AF-0]
	_ = x[BC-1]
	_ = x[DE-2]
	_ = x[HL-3]
}

const _MultiRegister_name = "AFBCDEHL"

var _MultiRegister_index = [...]uint8{0, 2, 4, 6, 8}

func (i MultiRegister) String() string {
	if i < 0 || i >= MultiRegister(len(_MultiRegister_index)-1) {
		return "MultiRegister(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MultiRegister_name[_MultiRegister_index[i]:_MultiRegister_index[i+1]]
}
